name: Main Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  formatting:
    - uses: actions/checkout@v3
    - uses: volta-cli/action@v3
    - run: yarn install
    - run: yarn format:check
     
  build_interpreter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3
      - run: yarn install
      - run: (cd packages/lox-interpreter && yarn test)
